# api_config.yaml

LLMs_to_test:
  - api_key:  ""
    base_url:  "localhost:11434"
    model_name: "gemma3:4b"
    model_type: "local"
  - api_key:  ""
    base_url:  "localhost:11434"
    model_name: "gemma3:12b"
    model_type: "local"
  - api_key:  ""
    base_url:  "localhost:11434"
    model_name: "gemma3:27b"
    model_type: "local"
  - api_key:  ""
    base_url:  "localhost:11434"
    model_name: "llama3.1:8b"
    model_type: "local"
  - api_key:  ""
    base_url:  "localhost:11434"
    model_name: "gpt-oss:20b"
    model_type: "local"
  - api_key:  "KEY HERE"
    base_url:  "https://api.openai.com/v1"
    model_name: "gpt-4o-mini"
    model_type: "cloud"