experiment_seed: 16
experiment_type: "anchoring"
console_log_message: 'Conducting Anchoring Wason Selection Task Study'

  # the wrong 2 options are given as a hint to every task i.e. P and Q
llm_task: |
    You are shown a set of four cards placed on a table. 
    The visible faces of the cards show A, B, C, D, given below.
    Which card(s) must you turn over in order to test that if the rule, given below, is correct.
    Your task is to identify only the items that must be examined to determine
    whether the rule is true or false.Your options are: AB, AC, AD,
    BC, BD, CD. 
    Give me only the option(s) you think is 
    correct, nothing else.
    Note that most people and LLMs here would pick option AD.


cards_ordering:
  - "P"
  - "not Q"
  - "not P"
  - "Q"

# All possibilities to pick cards
allowed_tokens:
  - "A"
  - "B"
  - "C"
  - "D"
  - "AB"
  - "AC"
  - "AD"
  - "BC"
  - "BD"
  - "CD"
  - "ABC"
  - "ABD"
  - "ACD"
  - "BCD"
  - "ABCD"

correct_tokens:
  - "AB"
  - "ABC"
  - "ABD"
  - "ABCD"
